#1 day1 solution
lsug/advent-of-code-typelevel pull request #4
Opened 2020-02-22 16:25 UTC by KXA194

Solved Day1 puzzle but failed to pass one of the tests.

2020-02-22 16:58 UTC, zainab-ali requested changes
Thanks @KXA194 !  Could you fetch the latest changes from master?  There was a typo in the test that should be fixed there.

2020-02-22 16:58 UTC, zainab-ali commented on src/main/scala/advent/solutions/Day1.scala
> +    @tailrec
Awesome use of `@tailrec` :smile:

2020-02-22 16:58 UTC, zainab-ali commented on src/main/scala/advent/solutions/Day1.scala
>  /** Day 1: The Tyranny of the Rocket Equation
I've added a formatter (`scalafmt`) so we'll not need to worry about formatting changes.  Could you fetch the most recent changes and then run `sbt scalafmtAll`?

2020-02-23 09:36 UTC, KXA194 commented
I've re-submitted a new pull request. Sorry for screwing up with git. 😄

2020-02-24 10:07 UTC, zainab-ali commented
Closing as solved by #8

2020-02-24 10:07 UTC, closed without merging